### ISSUE TITLE
Please do not include your private input in the repo

### ISSUE THREAD

**Issue by RaczeQ** [henryiii/aoc2023#1]
https://www.reddit.com/r/adventofcode/comments/k99rod/sharing_input_data_were_we_requested_not_to/

Although purging old repos isn't expected by the users, the author asks not to publish your private input in any form.
It's intended to prevent bulk scraping of many inputs and try to reverse-engineer the puzzle.

**Comment by henryiii** [comment]
I’d already noticed this request in the docs last night and wiped the history this morning. Future inputs won’t show up here. Thanks!
